keys:
  - &gpg 81EF72D465F4A067F36306D4BD7AAB3588525C4B
  - &ssh ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID6o+DSTJkGTzxKUdRUL1snrBKhV2t7NIEqN7Y9sPGdq s@sirajh.com
  # age file should live at ~/.config/age/keys.txt on linux or ~/Library/Application Support/age/keys.txt on macOS
  - &age age1r3hz6f5x56uen556k6vmarmtnxcftc0yjrzsxgzpssavzalwp3xsxkp7hv

creation_rules:
  - path_regex: secrets.yaml
    # encrypt for all three recipients, decrypt with any one corresponding private key
    key_groups:
      - age:
          - *age
          - *ssh
        pgp:
          - *gpg
