set -g @plugin 'tmux-plugins/tpm'

# leader key
unbind C-b
set -g prefix C-f

# start windows and panes at 1, not 0
set -g base-index 1
set-option -g renumber-windows on
set -g pane-base-index 1

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -g mouse on
set -g status-position top
set -g status-style 'bg=default,fg=default'
set -g status-left '[#S] '
set -g status-right ''
set -g window-status-format ' #W '
set -g window-status-current-format ' #W '
set -g window-status-style 'fg=colour8,bg=default'
set -g window-status-current-style 'fg=colour7,bg=default'
set -g status-left '#{?client_prefix,#[fg=colour2],#[fg=default]}[#S]#[fg=default]  '

bind C-w new-window
bind C-o split-window -h -c "#{pane_current_path}"
bind C-v split-window -v -c "#{pane_current_path}"
bind C-p previous-window
bind C-n next-window
bind C-x kill-pane
bind x kill-window
bind r command-prompt -I "#W" "rename-window '%%'"

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
